"""risk domain schema

Revision ID: 3740c0e2bb3e
Revises: 51eb655a66bf
Create Date: 2026-09-23 21:10:12.301377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3740c0e2bb3e'
down_revision: Union[str, Sequence[str], None] = '51eb655a66bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_sync_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_synced_event_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('forecast_id', sa.String(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lead_min_hours', sa.Float(), nullable=False),
    sa.Column('horizon_hours', sa.Float(), nullable=False),
    sa.Column('prediction_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('decision_status', sa.String(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_health', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_decision_status'), 'risks', ['decision_status'], unique=False)
    op.create_index(op.f('ix_risks_prediction_window_start'), 'risks', ['prediction_window_start'], unique=False)
    op.create_index(op.f('ix_risks_priority_score'), 'risks', ['priority_score'], unique=False)
    op.create_index(op.f('ix_risks_risk_level'), 'risks', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risks_risk_type'), 'risks', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risks_target_id'), 'risks', ['target_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('risk_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_risk_id'), 'risk_decisions', ['risk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_decisions_risk_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_risks_target_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_type'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_level'), table_name='risks')
    op.drop_index(op.f('ix_risks_priority_score'), table_name='risks')
    op.drop_index(op.f('ix_risks_prediction_window_start'), table_name='risks')
    op.drop_index(op.f('ix_risks_decision_status'), table_name='risks')
    op.drop_table('risks')
    op.drop_table('risk_sync_state')
    # ### end Alembic commands ###
