"""work order schema

Revision ID: 5ff35b41e60d
Revises: 3740c0e2bb3e
Create Date: 2026-09-23 22:03:02.699770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff35b41e60d'
down_revision: Union[str, Sequence[str], None] = '3740c0e2bb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_number', sa.String(), nullable=False),
    sa.Column('source_risk_id', sa.String(), nullable=True),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('work_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['source_risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_created_at'), 'work_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_orders_display_number'), 'work_orders', ['display_number'], unique=True)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_display_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_created_at'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
