"""sensor channel schema

Revision ID: 683c63a88fea
Revises: 3df3b3280efc
Create Date: 2026-09-23 10:59:39.044473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683c63a88fea'
down_revision: Union[str, Sequence[str], None] = '3df3b3280efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('sensor_type_id', sa.String(), nullable=False),
    sa.Column('system_type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('hierarchy_node_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['hierarchy_node_id'], ['hierarchy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_channels_channel_id'), 'sensor_channels', ['channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_channels_channel_id'), table_name='sensor_channels')
    op.drop_table('sensor_channels')
    # ### end Alembic commands ###
