"""replay schema

Revision ID: 7a18ed72ff8c
Revises: b158b8ee4d18
Create Date: 2026-09-23 16:03:57.334223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a18ed72ff8c'
down_revision: Union[str, Sequence[str], None] = 'b158b8ee4d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('virtual_cursor', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'sensor_readings',
        sa.Column('origin', sa.String(), nullable=False, server_default='historical'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'origin')
    op.drop_table('replay_state')
    # ### end Alembic commands ###
