"""sensor reading schema

Revision ID: b158b8ee4d18
Revises: 683c63a88fea
Create Date: 2026-09-23 11:06:03.767615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b158b8ee4d18'
down_revision: Union[str, Sequence[str], None] = '683c63a88fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_ingested_sources',
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_path')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_alarm', sa.Boolean(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_channel_id'), 'sensor_readings', ['channel_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_occurred_at'), 'sensor_readings', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_occurred_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_channel_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('etl_ingested_sources')
    # ### end Alembic commands ###
