"""ods journal schema

Revision ID: d1aa14e94b6b
Revises: 7a18ed72ff8c
Create Date: 2026-09-23 16:23:59.675965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1aa14e94b6b'
down_revision: Union[str, Sequence[str], None] = '7a18ed72ff8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_provider_runs',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('ods_journal_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('system_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ods_journal_entries')
    op.drop_table('synthetic_provider_runs')
    # ### end Alembic commands ###
